In [7]:
import pandas as pd

path = "/home/teshbek/Work/Climate_Project/Wind/data/target.parquet"

# Load (requires either 'pyarrow' or 'fastparquet')
df = pd.read_parquet(path, engine="fastparquet")  # or engine="fastparquet"

# Optional: better display in notebooks
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 0)

# Quick look
print("Shape:", df.shape)
display(df.head(10))  # if not in a notebook, use: print(df.head(10))
print("\nDtypes:\n", df.dtypes)

Shape: (172653654, 6)

        time station_name    y       lat  lon  height
0 1976-12-31      тегюлтя  0.0  59.99952  0.0   173.0
1 1976-12-31      тегюлтя  0.0  59.99952  0.0   173.0
2 1976-12-31      тегюлтя  0.0  59.99952  0.0   173.0
3 1977-01-01      тегюлтя  0.0  59.99952  0.0   173.0
4 1977-01-01      тегюлтя  0.0  59.99952  0.0   173.0
5 1977-01-01      тегюлтя  1.0  59.99952  0.0   173.0
6 1977-01-01      тегюлтя  0.0  59.99952  0.0   173.0
7 1977-01-01      тегюлтя  0.0  59.99952  0.0   173.0
8 1977-01-01      тегюлтя  0.0  59.99952  0.0   173.0
9 1977-01-01      тегюлтя  0.0  59.99952  0.0   173.0

Dtypes:
 time            datetime64[ns]
station_name            object
y                      float64
lat                    float64
lon                    float64
height                 float64
dtype: object

In [10]:
df[df['y']>0]

                time station_name         y       lat  lon  height
5         1977-01-01      тегюлтя  1.000000  59.99952  0.0   173.0
29        1977-01-04      тегюлтя  1.000000  59.99952  0.0   173.0
56        1977-01-07      тегюлтя  4.000000  59.99952  0.0   173.0
57        1977-01-07      тегюлтя  1.000000  59.99952  0.0   173.0
58        1977-01-07      тегюлтя  4.000000  59.99952  0.0   173.0
...              ...          ...       ...       ...  ...     ...
172653649 1963-01-23  56741099999  4.115520  25.23351  0.0     NaN
172653650 1963-01-24  56741099999  5.092956  25.23351  0.0     NaN
172653651 1963-01-25  56741099999  3.086640  25.23351  0.0     NaN
172653652 1963-01-26  56741099999  5.092956  25.23351  0.0     NaN
172653653 1963-01-27  56741099999  3.086640  25.23351  0.0     NaN

[170268928 rows x 6 columns]